---
title: "p8105_hw5_tj2519"
output: github_document
date: "2023-11-08"
---

# Problem 0: load library
```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 1
## create the new variable
```{r}
pro1_df = 
  read_csv("data_p1/homicide-data.csv") %>% 
  mutate(city_state = paste(city, state, sep = ", ")) %>% 
  mutate(city_state = str_replace(city_state,"Tulsa, AL", "Tulsa, OK"))

```

## summarize dataset & Baltimore
```{r}
clean_df = pro1_df %>% 
  mutate(disposition = 
           ifelse(disposition %in% c("Closed without arrest", "Open/No arrest"), "Unsolved homicides", "Solved homicides")) %>%
  group_by(city_state, disposition) %>% 
  summarize(obs = n()) %>% 
  pivot_wider(names_from = "disposition", values_from = "obs") %>% 
  janitor::clean_names() %>% 
  mutate(total = sum(solved_homicides, unsolved_homicides))

bal = clean_df %>% 
  filter(city_state == "Baltimore, MD")
  
results = 
  prop.test(pull(bal, solved_homicides), pull(bal, total), conf.level = 0.95) %>% 
  broom::tidy() %>% 
  janitor::clean_names() %>% 
  select(estimate, conf_low, conf_high)
  
```


##for each city, calculate the prop
```{r}
prop = function(df) {
  
  results = 
  prop.test(pull(df, solved_homicides), pull(df, total), conf.level = 0.95) %>% 
  broom::tidy() %>% 
  janitor::clean_names() %>% 
  select(estimate, conf_low, conf_high)
  
  results
}


clean_df_nest =
  nest(clean_df, data = solved_homicides:total) %>% 
  mutate(results = map(data, prop)) %>% 
  unnest(data) %>% 
  unnest(results) %>% 
  select(-solved_homicides)


```

## plot
```{r}
clean_df_nest %>% 
  mutate(city_state = forcats::fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate, fill = city_state)) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = conf_low, ymax = conf_high))
```





# Problem 2
```{r}

```



